### ISSUE TITLE
find another name for `map` operation

### ISSUE THREAD

**Issue by gaspard** [cerebral/overmind#103]
Hi everyone, if you have an opinion on changing the name of the `map` operation, please add a comment with your proposition and people will vote after some discussion using the thumbs up reaction on the comment :-)

**Comment by garth** [comment]
I propose to leave it as `map` as this is commonly used in streaming/events libraries such as [RxJS](https://github.com/Reactive-Extensions/RxJS) and [callbag](https://github.com/staltz/callbag-basics). So in the context of actions (events) it should already be understood.

**Comment by reflog** [comment]
I'd vote for leaving it as `map`. It a familiar term in chains/streams and I think it's appropriate here. Plus, `transform` is too long :)

**Comment by garth** [comment]
@gaspard actions are more like event streams, which is why we can do things like `debounce`. This implies that this thing can happen many times. Which is why I think that `map` is more appropriate in this case. This is a concept that should be understood, and if not we can help by using the same term that other libs are using.

**Comment by gaspard** [comment]
Thank you all for these great comments and for having taken the time to convince me.

Now, each time I'll write `map` in an overmind app, I'll like this word a little more because it will remind me of you guys and your patience to share your thoughts 🙏🏼

So `map` it is and stays 😊
