### ISSUE TITLE
to track or not to track 

### ISSUE THREAD

**Issue by fopsdev** [cerebral/overmind#135]
hi guys

i came across a use case where pausing and resuming the tracking of state paths would be beneficial.

### usecase

imagine a table with multiple rows which supports the following features (simplified for now):
- sorting
- inplace editing of the cells

now imagine we have the following table sorted by column ```Name```:

```
Id    Name
1     Anthony
2     Beat
```

lets say our state that holds the rows looks like:
```js
myRows:
{
1:{Id:1,Name:"Anthony"},
2: {Id:2, Name:"Beat"
}
```
after rendering the tracked paths will contain: 
```
myRows.1
myRows.1.Name
myRows.2
myRows.2.Name
```
(because the sorting method accessed those paths)

now inplace editing the table to:

```
Id    Name
1     Christian
2     Beat
```

will result in the table to be immediately flipped over to:

```
Id    Name
2     Beat
1     Christian
```
because of the sorting

This is not a good user experience. What i would like is that the sorting just happens after explicitly clicking on the column header and not right after editing a cell. 

if i now could something like
```js
app.pauseTracking()
dotheSortingThingy()
app.resumeTracking()
```
those paths wouldn't be tracked and my use case would be fine :)

**Comment by etienne-dldc** [comment]
Hi 👋 

# About the proposal

I don't think this is a good idea, mainly for two reasons: 

## 1 - Path tracking is an implementation details

The notion of Path Tracking is not something the user (user === dev using overmind) is supposed to know about, it's how we do it but not how we present it to the user.

## 2 - This could lead to serious bug way too easily

What if the user forget to call `resumeTracking` ? What if you use a library and call some of it's stuff while the path tracking is paused ?

# About the use case

IMO, you are using the wrong state here. Either you decide that your rows are sorted by name (with a `currentSortCriteria` state), in that case they are sorted at all time (and I agree with you it's not a great UX when the user update something), or you want the re-order to happend only when the user click the header and in that case you need an state that store the order of the row and not the criteria.

So in my opinion the simplest solution to this is to add a `order` state that would store the order of the colum at any point in time.
Then clicking on a column header would update that `order` state using the values when the user clicked and this state would not change until the user click on another header.

**Comment by fopsdev** [comment]
Hey etienne

Thanks for taking your time. Its highly appreciated.
I totally see the benefit of a separate ```order``` state. It can come in handy as well lateron when introducing a "Add a new Row at the End" - Feature or so :)

But now lets have a look at it from a overmind-module-dev perspective.
Having this ```sorted``` state still means that we have maybe thousands  (think spreadsheet app, or reporting app, or...) of trackings which we will never use and are laid out in the memory for nothing.
Besides that the devtools somehow get crowded with this trackings as well.
If we would put that feature into proxy-state-tree and don't expose in the public api all performance savy lib-developers could benefit from it?

**Comment by etienne-dldc** [comment]
> we have maybe thousands of trackings which we will never use

I don't get that part... you would use the`order` state with the solution I proposed.

Here is what the render would look like: 

```js
const Row = ({ app }) => {
  const row = app.state.rows[rowId];
  return (
    <RowWrapper>
      {row.content}
    </RowWrapper>
  )
}

const Table = ({ app }) => {
  return (
    <Wrapper>
      {app.state.rowOrder.map(rowId => <Row key={rowId} rowId={rowId} />)}
    </Wrapper>
  )
}
```

And this would be very well optimized because `Table` tracks only the `rowOrder` and each `Row` tracks only the row it render.
And yes if there are a 1000 row, the `Table` will track a 1000 paths but if that's a problem then you should optimize for example by rendering only the visible rows with something like `react-window`.

As for devtools, I agree that it get crowded in some cases but that's a devtools issue I think, not an API issue.

**Comment by fopsdev** [comment]
> > we have maybe thousands of trackings which we will never use
> 
> I don't get that part... you would use the`order` state with the solution I proposed.

my component (btw. its a custom element v1 vanilla implementation with a little help of lit-html and of course overmind :) ) should only reorder when a: the column changes or b: the sort order (ascending/descending) changes. imo tracking those instead of the 1000's of ```order``` states should be enough

**Comment by etienne-dldc** [comment]
Yeah but that's not what you want in your usecase. In order to be able to display the row in the order they were before the rename you have to keep this order somewhere.
Otherwise you will break the relation between `state <=> view`.

If you were able to `pause` / `resume` tracking and use it as you describe, your component would become unpredictable, for example if you had this state: 

```
myRows: [
  { id: 1, name: "Christian" },
  { id: 2, name: "Beat" },
],
sortBy: 'Name'
```

Then you couldn't tell me what the render is because you don't know if there was a rename made after the sort.
While if you store the order: 
```
myRows: [
  { id: 1, name: "Christian" },
  { id: 2, name: "Beat" },
],
rowOrder: [1, 0]
```
You know exactly what to render.
Note that you probably also need to store the selected order criteria to display it in the UI and also to potentially detect when the order is out of date and aks the user if he want to update the sort.

> imo tracking those instead of the 1000's of order states should be enough

Yes but only if you don't plan to add or remove rows. Overmind make the choice not to let the user decide what it tracked and instead track everything that is used and because the tracking of overmind is super precise (thanks to Proxies) it's almost always the most optimized solution and when it's not it's probably a good sign that you are doing something wrong (again, if you track 1000's of stuff, it mean you are rendering 1000's of stuff... which is not ideal)

**Comment by fopsdev** [comment]
hi again and thanks for your pointers :)

yeah i'm already storing the ```rowOrder``` inside my component so thats all fine.
it's all about recalculate this ```rowOrder``` order when one of the order criterias changes.
btw. even using "react-window" - principle  you have to filter and sort the full resultset somehow.
would be nice to get some more opinions on this one, so i leave it open for now

**Comment by fopsdev** [comment]
Changed the title of this issue. i have found a way to prepare lists without tracking all the containing cells (rows/columns) in my custom-element.
but still the question remains. how should something like this be handled.
It got even more delicate now that i have included a table-filter (a filter which looks through all the cells in a table). 
my current solution is that my base component calls a prepareUI() - method  which is not tracked.
i had a another solution in place which was operating on the original state (not even proxified) but then of course i had to rebuild the derive-functionality which was sort of a no-go.

**Comment by christianalfoni** [comment]
Closing as we have solved this :)

**Comment by fopsdev** [comment]
Just for completeness sake.
I have an action now which creates the new sorted rows (ids) whenever a user changed the filter or whenever the user changes the sorting.
this sorted rows is also saved in state giving nice insights using devtools.
the components just point to this sorted rows and just update fine now when the user really is requesting it.
