### ISSUE TITLE
Question: Any plans to introducing patches?

### ISSUE THREAD

**Issue by carlosagsmendes** [cerebral/overmind#195]
Any plans to introduce patches? Thanks in advance

**Comment by christianalfoni** [comment]
Hi there!

You mean patching the state tree? Could I ask what you specifically use it for? Just have to make sure we go forward actually solving issues, not just adding features :)

**Comment by carlosagsmendes** [comment]
Hi @christianalfoni, 

I'm just trying to understand if it this is part of your plans.

The use case is [distributing state changes](https://medium.com/@mweststrate/distributing-state-changes-using-snapshots-patches-and-actions-part-2-2f50d8363988) between multiple end users that are editing the same tree, for example, a shared task list, kanban board, etc.

Thank you

**Comment by christianalfoni** [comment]
Thanks for the use case @carlosagsmendes :)

I believe this can be done by someone creating an addon to Overmind. Everything you need is there, it just needs to be implemented. So you can imagine someone creating an API like:

```ts
const config = merge(myConfig, operationalTransformAddon({
  pathToSync: '',
  ....
}))
```

Cause you can listen to any mutations in Overmind, at what path they happen and exactly what kind of mutation it was with accompanying arguments.

https://www.overmindjs.org/api/overmind#overmind-addmutationlistener

Though it does requires a lot of considerations etc. The idea of Overmind is that we take on the maintenance burden of the project itself and the devtool. Everything beyond that we want to be built in userland or it will hurt the project due to have taken on too much responsibilities. Learned that from previous projects :)

So short answer. Yes, it is possible, but sorry to say we are not going to build it in the core team. This will have to be built in user land. We are happy to help though :)
