### ISSUE TITLE
Vue code smells

### ISSUE THREAD

**Issue by TheJaredWilcurt** [cerebral/overmind#197]
The Vue code examples look like they were the first time someone ever used Vue. Here are some tips to clean up code smells:

* In the Vue world you have things like `v-on:click="doThing"` and `v-bind:title="dataValue"` and then you have the shorthand versions of these, `@click="doThing"` and `:title="dataValue"`. And litterally *everyone* just uses the shorthand. You are using a mix of the two, just use the shorthand.
* You are importing `connect` in every Vue component and then wrapping the `export default` in the connect. Gross. Don't do that. Follow the pattern that Vuex (and other global things like Vue-i18n, Vue-Router, etc) uses. In the `overmind.js`
  ```js
  import Vue from 'vue';
  import { Overmind } from "overmind";
  import { createConnect } from "overmind-vue";
  Vue.use(Overmind);
  const overmind = new Overmind({
    state: {
      isLoadingPosts: true
    }
  });
  export const connect = createConnect(overmind);
  ```
  in `main.js`
  ```js
  import Vue from 'vue';
  import store from './overmind.js';
  const app = new Vue({
    store
    // ...
  });
  ```
  Or something similar to that pattern.
* In the template section put a space inside double curly braces. `{{ todo.title }}`
* Feels weird to have to baby sit Overmind by manually adding and removing mutation listeners.
* Not seeing any dev tools examples. Vuex is built in to Vue devtools and is very handy for inspecting the current state or even modifying the state directly.

**Comment by edgesoft** [comment]
@TheJaredWilcurt Maybe you could create a PR for this?

**Comment by christianalfoni** [comment]
@TheJaredWilcurt This is super helpful, thanks a bunch. You are perfectly right that the API hurts in lack of Vue experience, but this certainly points out the issues. Let me do a refactor of this :)

Though could you point out what you mean by: "Feels weird to have to baby sit Overmind by manually adding and removing mutation listeners"?

Adding mutation listeners is only related to reacting to certain state changes. Like if you have a Codemirror instance related to your component, you want to imperatively call methods on that codemirror instance related to some state change for example. The components renders automatically with the state used in the templates.

**Comment by christianalfoni** [comment]
Also the website has been revamped now, running at https://next.overmindjs.org until release. Please check: https://next.overmindjs.org/guides/beginner/08_usingovermindwithvue for an updated guide on connecting.

This actually made one of my dreams come true... hook Overmind at one point and just use your components, do not worry about tracking or exposing state, actions etc. at all :-)

**Comment by christianalfoni** [comment]
Also made a video :) https://www.youtube.com/watch?v=VCQCEERl2b0

**Comment by TheJaredWilcurt** [comment]
👏 👍 

Yeah, that's great. Looks a lot better. Docs look good.

From watching the video a few notes:

* I actually like the API of `actions.add(3)` more than `commit('add', 3)`. Always seemed weird to pass in a string of the name of a method.
* You seemed a bit confused on why `computed` was being used. Computed values are actually really logical for state management. But maybe not as needed in overmind? I made a short video explaining computed values:
  * https://www.youtube.com/watch?v=jjeH7wgzNJ4
  * TLDW: They run once and cache the results and everything else gets the cached results
  * In Vuex the "state" is like the data section in a component, except shared across many components. In the same way, "getters" are like shared computed values.
* Would be nice if the dev tools were built into the browser via chrome-extension. Electron is pretty 💩 

Welcome to the Vue party! 🎈 🎉 

* https://vue-land.js.org

**Comment by christianalfoni** [comment]
Thanks again for the feedback @TheJaredWilcurt , this will be released tomorrow then :)

- Great! Me too :)
- Yeah, to be more specific about my confusion: It seemed to me that you had to use `computed` with Vuex to make the values reactive or something? Cause that simple example there would really not need caching of value. But you could also then use: `data: () => ({ count: store.state.count })`? Overmind also has computed, though it is called derived and is defined in the tree with the other values: https://www.overmindjs.org/api/derive
- The previous state management tool I worked on was Cerebral and i started out with a browser extension. It is such a pain to manage for the following reasons:
  - You have to install it as extension on your browser, now you just `npx overmind-devtools`
  - since it is browser extension it does not work on all browsers
  - A hassle to release automatically with the rest of the project. Now it is just an NPM package like everything else
  - Does not working with Native tools or server side execution
  - It isolates you from moving to new features like creating test files automatically, even start a new project from the tool etc. So many thing this stuff can do... a browser extension just restricts the imagination :)

But I totally see that it is convenient.. though there you got at least some reason why we choose to use Electron :)
