### ISSUE TITLE
Code sharing with mobx

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#203]
Just curious, we use immer/mobx. Is this / will this use the same low level libraries? Just curious overhead of adding this as well.

**Comment by christianalfoni** [comment]
Overmind is using a custom proxy implementation called [proxy-state-tree](https://github.com/cerebral/overmind/tree/next/packages/node_modules/proxy-state-tree). The reason is that we are not observing values, we are observing paths in the state tree. This allows for much better tracking of mutations and what components are actually looking at.

So these libraries does not share anything. It would be 12kb (using overmind and overmind-react) added to your bundle size :)

**Comment by natew** [comment]
Thanks!
