### ISSUE TITLE
Unnecessary mutations

### ISSUE THREAD

**Issue by luisherranz** [cerebral/overmind#220]
I'm studying Overmind and everything seems so carefully planned that one thing surprised me:  mutating the same part of the state with the same value *does trigger* a new mutation.

I'll show it with an example:

```js
// store.js
const overmind = new Overmind({
  onInitialize: ({ value }) => {
    value.addMutationListener(mutation => console.log(mutation));
  },
  state: {
    name: 'John'
  },
  actions: {
    changeName: ({ state }) => {
      state.name = 'Peter';
    }
  }
});

// Name.js
function Name() {
  const { state } = useOvermind();
  console.log('<Name /> rendered');
  return <h1>Hello {state.name}</h1>;
}

// App.js
function App() {
  const { actions } = useOvermind();
  return (
    <div className="App">
      <Name />
      <button onClick={actions.changeName}>Change name to Peter</button>
    </div>
  );
}
```

Clicking on the `<button>` triggers a new mutation and a new (unnecessary) re-render of the `<Name />` component.

Logs are:
```
Object {method: "set", path: "name", args: ["Peter"]}
<Name /> rendered
Object {method: "set", path: "name", args: ["Peter"]}
<Name /> rendered
Object {method: "set", path: "name", args: ["Peter"]}
<Name /> rendered
...
```

codesandbox: https://codesandbox.io/s/7wjj165ynq

I saw the same behaviour in ProxyStateTree: https://codesandbox.io/s/3846ww49qq (I modified the `toggleItemCompleted` action)

I'm used to Mobx, which doesn't trigger mutations if the value doesn't change, not matter what you do.

How's this going to work in Overmind/ProxyStateTree? Have you already thought about the overhead of comparing those scalar values vs the performance gains derived from avoiding those unnecessary re-renders?

**Comment by fopsdev** [comment]
Hi there

I'm honestly not sure if it would be beneficial to inlcude a check.
One reason i moved to cerebral/overmind was because there was too much magic in other frameworks.
Maybe we should put together use cases to make it more clear.
Maybe reasons to leave this to the developer would be (really just from the top of my head):
- Forced rerenders by setting the same state again
- stock quote action(effect) where stock quote gets set to the same value but list should rerender and displays timestamp of that stock quote

**Comment by luisherranz** [comment]
> One reason i moved to cerebral/overmind was because there was too much magic in other frameworks.

I think "reducing magic" is not the main goal of overmind, but to improve the developer experience.

In that regard, I don't see a good developer experience in things like this:
```js
const changePost = ({ state }, { id, title, content, featuredImageId, excerpt, authorId, date... }) => {
  if (state.post[id].title !== title) state.post[id].title = title;
  if (state.post[id].content !== content) state.post[id].content = content;
  if (state.post[id].featuredImageId !== featuredImageId) state.post[id].featuredImageId = featuredImageId;
  if (state.post[id].excerpt !== excerpt) state.post[id].excerpt = excerpt;
  if (state.post[id].authorId !== authorId) state.post[id].authorId = authorId;
  if (state.post[id].date !== date) state.post[id].date = date;
  // and so on...
};
```
instead of just doing:
```js
const changePost = ({ state }, post) => { state.post[id] = post };
```
I think Overmind should take care of calculating the minimum amount of mutations (and component rerenders) in any situation.

**Comment by fopsdev** [comment]
Yeah, thats definitely a lot of code which could be saved :)

my use cases as mentioned before are sort of crappy and there was no other use case popping up in my mind until now. 
Thinking more about it and having developer experience AND render perfromance in mind i also think this would be a really great improvement to add this (deep) checking into overmind

**Comment by christianalfoni** [comment]
Hi guys!

Yeah, we did discuss this a bit back and forth. It is actually not as straight forward as one might think :)

The question is what are we actually going to prevent. That the mutation occurs at all? Or that we just ignore it related to "flushes" (component notifications).

If we ignore that mutation completely it will not even appear in the devtools, which I think is wrong. You are changing the state, even though to the same value. Avoiding the mutation all together can cause confusion. Same would be for testing.

But lets say we do show the mutation in the devtools and rather just filter it out on flush. The problem now is that you see that you did a mutation, but the devtools shows no components were affected... there is nothing indicating that this happened because you changed to the same value.

Optimizations is always nice, but we have to balance it out with how it is interpreted by the developer, not only the computer :) I can not imagine a scenario where replacing a value with the same value would be a performance issue. And if it is, you will clearly see it in the devtools and you can do that optimization in that edge case.

Did this make sense? :) I do not disagree that it is a good optimization, but it is magical, hidden from the developer, causing unpredicted behaviour. To make such an optimization we also need to handle these other concerns at least.

Thanks for bringing it to our attention though and please bring in more points so we can discuss it further. Not saying this as a "No, we will not do it" :)

**Comment by luisherranz** [comment]
Good points! Let me rebut :)

> If we ignore that mutation completely it will not even appear in the devtools, which I think is wrong.

I do not quite agree with the fact that ignoring those unnecessary mutations will lead to a bad developer experience. At least that's not my experience:

- I worked with Meteor a lot (back in those days) and `ReactiveVar` already worked that way:
`An important property of ReactiveVars — which is sometimes a reason for using one — is that setting the value to the same value as before has no effect; it does not trigger any invalidations.`
https://docs.meteor.com/api/reactive-var.html
I never saw anyone having problems with this in the Meteor community.

- Mobx (and therefore MobxStateTree) also work that way and I've never seen issues or questions that lead to any problem related with ignoring those mutations.

But: **I agree with the fact that showing those mutations in the devtools is better than not showing them at all.**

> I can not imagine a scenario where replacing a value with the same value would be a performance issue.

I've been there, and I can assure you this is a problem. An ugly one. Maybe only in complex apps and maybe only in mobile, but I've been there and unnecessary rerenders are a real performance problem which is both hard to find and hard to fix. When we migrated from Redux to MobxStateTree this was such a bless. For me the Mobx's *no matter what you do, you can't cause unnecessary rerenders* is the best developer experience possible.

Unnecessary mutations may also lead to more complex and bug-prone code for side effects that need to be run only when something *actually* changes, like database updates, analytics, url updates and so on:

```js
let oldUrl = '';
overmind.addMutationListener(({ path, args }) => {
  if (path === 'state.url' && args[0] !== oldUrl) { // you need to check if the mutation is a real mutation
    oldUrl = args[0]; // you need to save the value to check it later
    history.pushState(args[0]);
  }
})
```

Instead of just:
```js
overmind.addMutationListener(({ path, args }) => {
  if (path === 'state.url') history.pushState(args[0]);
})
```

---- 

> I do not disagree that it is a good optimization, but it is magical, hidden from the developer, causing inconsistent behaviour.

I wonder if we can find the perfect solution. Something that:

1. Avoids unnecessary mutations
2. Doesn't hide them from the developer
3. Doesn't lead to inconsistent behaviour

The only thing that comes to my mind right now is to expose the ignored mutation in the devtools with a warning:

![screen shot 2019-02-11 at 12 18 16](https://user-images.githubusercontent.com/3305402/52562688-9ae32a80-2dff-11e9-970a-bb2ea0382430.png)

But I'm not sure how the component and flush part of the dev-tools may handle this.

Also, could you please ellaborate a bit more about what you mean by inconsistent behaviour?

**Comment by christianalfoni** [comment]
Hi again and thanks for following up on this, I am sure we will find a good solution and you made a great summary here :-)

What I meant by inconsistent behaviour is that some mutations behaves differently than others. But from a different perspective that is exactly what we want :-)

I was also thinking about just notifying in the devtools that the mutation was ignored, and it is possible. We could also make it an option, so that you opt in to a specific behaviour.

But okay, lets say we have two approaches here now:

1. We indicate that a mutation has been ignored
2. We add an option to the Overmind instance that opts in to ignoring mutations with same value

Option 1. here is definitely what we should go for, though we have to figure out how to best implement it.

So one suggestion here is:

1. When a mutation occurs in `proxy-state-tree` we attach the old and new value as part of the mutation information
2. This information is passed all the way up to Overmind populating the `mutation` events with this additional information. This information can also be used to tell the devtools that the old and new value is the same
3. When `proxy-state-tree` "flushes" out changes it will ignore mutations where the old and new value is the same

That means we are not ignoring the mutations really, we are just filtering out "same value" mutations when flushing out changes.

Does that make sense?

**Comment by luisherranz** [comment]
> Does that make sense?

Yes, it makes perfect sense :)

> This information can also be used to tell the devtools that the old and new value is the same

I'd even show previous and current value for each mutation. I remember that in Redux Devtools and it was very useful for debugging:

![screen shot 2019-02-11 at 12 18 16](https://user-images.githubusercontent.com/3305402/52705014-2c7aa580-2f82-11e9-83ec-7d91988ba619.png)

> When `proxy-state-tree` "flushes" out changes it will ignore mutations where the old and new value is the same

The last doubt I have is, can `proxy-state-tree` traverse the state object to check for changes in scalar values or would it work like an immutable store, where the whole object is thrown away when the reference changes?

This is what I mean:
```js
const state = { user: { firstName: 'Jon', lastName: 'Snow' } }

const changeUser = ({ state }, user) => {
  state.user = user
}

// trigger mutation:
changeUser({ firstName: 'Jon', lastName: 'Targaryen' })

// current mutation:
{ method: "set", path: "user", args: [{ firstName: 'Jon', lastName: 'Targaryen' } }]

// ideal (minimal) mutation:
{ method: "set", path: "user.lastName", args: ['Targaryen'] }
```

I'm not sure yet how the internals of `proxy-state-tree` work and how difficult would be to do this type of minimal mutation but, what are your thoughts about this?

**Comment by fopsdev** [comment]
Really like the proposal. Mutation Listener would also benefit from minimal Mutation

**Comment by christianalfoni** [comment]
Cool, will look into this for next release :)

**Comment by christianalfoni** [comment]
Okay, so I have implemented this now in `next`. I only skip notifying registered listeners when the value has not changed. It will still notify it as a mutation for mutation listerners, devtool etc... but with a `hasChangedValue` property telling if it actually changed value.

That way we can implement something in devtool to indicate it, but maybe not necessary. We will see.

**Comment by luisherranz** [comment]
Hey, sorry Christian. I've been super busy.

Is this it? https://github.com/cerebral/overmind/commit/2a350bed5e47e20345e1be5888026e17aa4cca6b Looks great! I'll check it out :)

**Comment by christianalfoni** [comment]
Jup, exactly! :)

I will just close this for now, just reopen or keep commenting if you have any questions. And no worries on being busy. I think we are both infected with the busy-virus ;-)
