### ISSUE TITLE
Bind this as context in actions and effects

### ISSUE THREAD

**Issue by gaspard** [cerebral/overmind#226]
We can inject the context as `this` in actions and effects to simplify actions and effects even more. This creates a very intuitive and clean api where there is no confusion as to argument order (context, value) or (value, context) and where helpers that do not require any context are just simple functions (without the need for an empty context slot):

Example:

```ts
export const createContact: Operator = action(function (type) { // no more arrow here
  const { data, dialog } = this.effects

  data.createContact(type)
  data.clearForm()
  dialog.show('ContactPrint')
})
```

For this idea to work, we need to remove `this` argument in effects:

```ts
interface Foo {
  (this: number, value: string): boolean
}

interface Bar {
  (value: string): boolean
}

type RemoveThis<T> = T extends (this: any, v: infer V) => infer U ? (value: V) => U : never

type Foo2 = RemoveThis<Foo> // (value: string) => boolean
type Bar2 = RemoveThis<Bar>// (value: string) => boolean
```

With this solution, the user has an added advantage to using effects (on top of devtools) because he/she does not have to care about passing the context around at all anymore.

**Comment by FWeinb** [comment]
I am split on this. I am using arrow functions everywhere nowadays and try to minimise mixing matching of anonymous and arrow functions. I do understand the different semantics but don't like the introduced complexity.  

This change would force every action/operator to be written as an anonymous function to get access to the context, because an arrow function can't be rebound to another `this`. 

Another thing I like about having the context in the signature is that one can list all the context dependencies though destructuring.

**Comment by gaspard** [comment]
Yes. I also don't like the anonymous function and the return of `this` as the bad boy in town 😂

This was more a thought that I thought needed to be explored. I also think simplicity should most of the time win on "elegance" where complexity is just hidden.

**Comment by gaspard** [comment]
PS: not having `this` special treatment also means that effect functions can be imported through `import` as usual and it just works the same (just without tracking).

**Comment by gaspard** [comment]
We all agree that we do not want **this** bad boy back
