### ISSUE TITLE
Set overmind as peerDependency in overmind-react and other packages

### ISSUE THREAD

**Issue by artemirq** [cerebral/overmind#227]
Because we cannot use `overmind-react` without `overmind`, we can set `overmind` as `peerDependency` in `overmind-react` and other same packages (`overmind-angular`, `overmind-vue`)

**Comment by christianalfoni** [comment]
Hi there!

This is always a big question, `dependency` or `peerDependency` :) 

`peerDependency` indicates like a plugin or middleware to my understanding. We do not consider the view libraries as "plugins", but rather libraries that has a hard dependency to. We want people to just do `npm install overmind-react` without having to think about installing `overmind ` as well... which is how it works now, as `overmind` is a `dependency` of the view libraries.

Does that make sense? Or you think we would get benefits of using `peerDependency`?

**Comment by artemirq** [comment]
@christianalfoni
Hi!

Not a big different

If we choose `peerDependency`, user can control, which `overmind` version he need with `overmind-x`
Example. I don't like new version `overmind 1.1.0` for some reasons, but like new version `overmind-x 1.1.0`. I want use `overmind-x 1.1.0` with `overmind 1.0.0`. And I can't this currently, because `overmind-x 1.1.0` required `overmind 1.1.0`

**Comment by luisherranz** [comment]
I was about to open this issue as well. With a peer dependency the use can choose what overmind version to install. It may not be `overmind: next` like it is right now. 

Also, I don't see a problem with `npm install overmind overmind-react` because it's a already a common pattern with many other tools: react and react-dom, mobx and mobx-react, redux and react-redux and so on...

**Comment by luisherranz** [comment]
By the way, you also need to add `react` as a peer dependency because you are importing it here:
https://github.com/cerebral/overmind/blob/next/packages/node_modules/overmind-react/src/index.ts#L24

Some tools will fail:
![screen shot 2019-02-12 at 08 20 57](https://user-images.githubusercontent.com/3305402/52618470-37a8d500-2e9f-11e9-8c29-23eda56bcc46.png)

I can do a PR for both if you want.

**Comment by christianalfoni** [comment]
Hm, yeah... versioning is difficult stuff. We had a lot of challenges with this in Cerebral and wanted a predictable system. So the way this works, and it is completely automatic, is that we bump the version of all packages that uses it as a dependency.

For example:

`proxy-state-tree` has a patch. `overmind` and all `overmind-xxx` packages also gets a patch. And same for other types of changes of course.

It might very well be possible that version 10 of `overmind` works with version 16 of `overmind-react`, or whatever, but it might also completely fail. After we changed to this system we have not had any problems. You will always work on compatible packages.

Does that make sense?

Noted about `react`, thanks :)

**Comment by artemirq** [comment]
@christianalfoni

If version 10 of `overmind` is incompatible with version 16 of `overmind-react`, we need to change minimal version in `peerDependencies` at `overmind-react`:

**package.json**
```
{
  "name": "overmind-react",
  "version": "16.0.0",
  "peerDependencies": {
    "overmind": "^16.0.0"
  }
}
```

Yeah, user can fault at use `overmind-react@16.0.0` with `overmind@10.0.0`, but here is a `peerDependencies` warning in console. If user going wrong way, it's not our fault, because NPM/Yarn tell about wrong dependency like this:

`warning "overmind-react@16.0.0" has incorrect peer dependency "overmind@^16.0.0"`

**Comment by christianalfoni** [comment]
Though @artemirq and @luisherranz, are you finding the current approach problematic? :-) Is this suggested change more of a principle? Cause if it is just a principle thing I think we should just stick with what we have, because we have had so many rounds on versioning issues and this approach works. We actually built a whole monorepo tool around this whole concept, which is used on both Cerebral and Overmind :)

But adding react, angular, vue etc... for the different packages as `peerDependencies` I totally agree with.

Please continue the discussion if I have overlooked any concerns here, but yeah, to my knowledge we have not had any issues with people installing wrong versions as they are all "locked in time" now, we guarantee that they work together... which I think is a really important promise :)

**Comment by luisherranz** [comment]
It's not problematic in most cases, it's just the way it's usually done in npm.

The only problem I see is a possible conflict in the case somebody wants to use a fork/alternative to the main `overmind` package (for a bug fix or added feature which is not in the official one). They would end up with an `overmind@next` from `overmind-react` and their own `overmind` version installed from GitHub or with a different name. They can solve it forking `overmind-react` as well so it's not a big deal.

**Comment by christianalfoni** [comment]
Cleanup 😄
