### ISSUE TITLE
Derived values behave inconsistently

### ISSUE THREAD

**Issue by sanohin** [cerebral/overmind#233]
Looked at the source, as I understand derived values are captured only during store creation. Any plans on handling dynamically added derived values?

And seems like they don't work in arrays, instead of state I get an instance of EventEmitter.

https://codesandbox.io/s/1wq8rxzvvj

**Comment by luisherranz** [comment]
Nested derived values should not be used/supported, at least with the current implementation of Overmind. 

The problem with nested derived values is that Overmind won't be able to handle rehydration because those derived state funtions are not serializable. `overmind.state` gives you the current state, but the object can't contain functions or it won't be useful to save it in a database, localStorage, sending it to the client after SSR, doing HMR and so on...

Following your example:
```js
const createItem = id => {
  return {
    id,
    selected: state => {
      return state.selectedId === id;
    }
  };
};

const overmind = new Overmind({
  state: {
    selectedId: 1,
    items: [createItem(1), createItem(2)]
  },
  ...
}
overmind.items[0].selected // <- This works now.

const currentState = overmind.state;
// {
//   selectedId: 1,
//   items: [{ id: 1 }, { id: 2 }]
// }
localStorage.setItem('myAppState', currentState);

// And later on...

const previousState = localStorage.getItem('myAppState');
overmind.rehydrate(previousState);
overmind.items[0].selected // <- Here this function doesn't exist anymore.
```

A serializable and rehydratable state is key in any state manager and I understand you may not need to rehydrate your App right now, but when `overmind.rehydrate` is implemented it's going to be diffucult to explain that it won't work properly if you use nested derived state in your app.

For those coming from MobxStateTree who are used to nested derived values (`views` in MST) it's kind of drawback and I've been wondering if there's something that can be done in Overmind without making the API more complex...

**Comment by fopsdev** [comment]
Yeah thats an interesting concern with serialization, would love what @christianalfoni  thinks about it.
Concerning adding calculated values after store creation => use a getter :)

**Comment by christianalfoni** [comment]
Hi guys :)

First of all derived needs to be static. The reason is because they cache. If we allowed them to be dynamic a lot of extra work would have to be done:

1. Whenever you add any value to the tree we would have to traverse everything to figure out if there are any functions there, to convert them to derived values. Maybe we could do this lazily, but then you would not know in the devtools what are derived values from the "get go"

2. Whenever you remove any value from the tree we would have to traverse everything to figure out if there are any derived there, to dispose them

This is a lot of unnecessary work :)

But most cases does not require a derived. Just use a `getter`:

https://www.overmindjs.org/guides/beginner/02_definingstate

The only reason to use derived is to cache heavy computation and/or access parent/sibling parts of the tree.

So in the case of the sandbox you do use `selectedItem`, instead of each item having a select. This is actually optimal cause now you can in your list component pass in a `isSelected` prop by checking `item === selectedItem`. If now each `ItemComponent` is a Pure component you ensure that only the `ItemComponent` that actually now is selected/unselected will render again. Instead of every single `ItemComponent` rendering again to check if they are now selected or not (cause all of them depend on the selectedId :)

Good point about hydrate/rehydrate as well, though populating data from the server with getters is perfectly okay :)

**Comment by luisherranz** [comment]
> Good point about hydrate/rehydrate as well, though populating data from the server with getters is perfectly okay :)

Awesome :)

So, the conclusion is:
 - we can use static derived values or getters.
 - we cannot use dynamic derived values or getters.

Static, good: 
```js
const state = {
  user: {
    id: 1,
    firstName: 'Bob',
    lastName: 'Jackson',
    get fullName() {
      return this.firstName + ' ' + this.lastName
    }
    expensiveName: ({ state }) => expensiveComputation(`${state.firstName} ${state.lastName}`)
  }
}
```

Dynamic, bad:
```js
const state = {
  users: {}
}
const actions = {
  addUser: ({ state }, { id, firstName, lastName }) => {
    state.users[id] = {
      id,
      firstName,
      lastName,
      get fullName() {
        return this.firstName + ' ' + this.lastName
      }
      expensiveName: ({ state }) => expensiveComputation(`${state.firstName} ${state.lastName}`)
    }
  }
}
```

This case must be solved with static derived values:
```js
const state = {
  users: {}
  userFullName: id => ({ state }) => `${state.users[id].firstName} ${state.users[id].lastName}`,
  expensiveUserName: id => ({ state }) => expensiveComputation(`${state.users[id].firstName} ${state.users[id].lastName}`)
}
const actions = {
  addUser: ({ state }, { id, firstName, lastName }) => {
    state.users[id] = { id, firstName, lastName }
  }
}
```

@christianalfoni is that right?

**Comment by christianalfoni** [comment]
@luisherranz Almost :-)

The last case would rather be:

```js
const state = {
  users: {}
}
const actions = {
  addUser: ({ state }, { id, firstName, lastName }) => {
    state.users[id] = { id, firstName, lastName, get fullName() { this.firstName + ' ' + this.lastName } }
  }
}
```

If you need to manage heavy computation and cache individually for each user you could rely on the component to do that. So you use for example memoize function inside the component to create the expensive name of the user, based on the ID of the user. When the component unmounts or when you remove the user from the state you could clean out the memoize cache. 

I consider this an extreme edge case though. Where you usually have heavy computation is related to lists, not on each item in the list. And if you have heavy computation on each item in a list it is likely related to the selected item, which means you can have a `selectedItemDerived`. 

Does that make sense? :)

We might be able to solve dynamic derived in an effective way in the future, though sometimes it leads to less optimal solutions. Like the "selected" example here, where you would benefit from rather having a "selectedItem" derived and then pass a "selected" prop to each ItemComponent :)

**Comment by luisherranz** [comment]
> The last case would rather be:
> ```js
> const state = {
>   users: {}
> }
> const actions = {
>  addUser: ({ state }, { id, firstName, lastName }) => {
>     state.users[id] = { id, firstName, lastName, get fullName() { this.firstName + ' ' + this.lastName > } }
>  }
> }
> ```

Will something like `state.users[0].fullName` work after `overmind.rehydrate`?

**Comment by christianalfoni** [comment]
@luisherranz Nopes, that would not work. Good point though!

Generally I prefer using helper functions for this kind of functionality, so that you rather do:

```
<div>{fullName(user)}</div>
```

That keeps your state serializable. You know, this is very interesting topic. We should really write a guide on making decisions when you define state. The current guide just shows you what you can do, not really the tradeoffs :)

**Comment by luisherranz** [comment]
Sure. If that becomes a problem maybe Overmind can warn you in the console that you may break rehydratation and an option to disable those warnings for people who are already aware but still want to use them.

**Comment by fopsdev** [comment]
> The current guide just shows you what you can do, not really the tradeoffs :)

Yeah that would quite enlightening :)
Maybe it belongs into the state guide: https://www.overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=true
It would also solve questions like: Can i put xy into state?

**Comment by sergeyzwezdin** [comment]
@luisherranz 

> Nested derived values should not be used/supported, at least with the current implementation of Overmind.

Why wasn't it specified in [docs](https://overmindjs.org/api-1/derive) explicitly? 🤔
