### ISSUE TITLE
Proposal: Operators to track state mutations

### ISSUE THREAD

**Issue by luisherranz** [cerebral/overmind#243]
## The problem: tracking state mutations

I really like Flux but in my experience, it has one flaw: sometimes you want to trigger a side-effect when some part of the state mutates. In Flux, everything has to be triggered by an action so you need to listen to all the actions that may mutate that state.

For example, in redux-saga, if you want to send an analytics event when `state.currentPage` changes you need to know all the actions that modify `state.currentPage`:
```js
function* currentPageChanged() {
  yield takeEvery([
    "HOME_PAGE",
    "ABOUT_PAGE",
    "DOCS_PAGE",
    "POST_PAGE",
    "LIST_OF_POSTS_PAGE",
    ...
  ], sendAnalyticsEvent)
}
```

Sometimes you can save the day consolidating all the actions in a single one: `CHANGE_PAGE`, but sometimes you just can't, the actions are too different or doesn't make sense to join them.

This pattern quickly leads to code that is difficult to maintain and prone to bugs: in this case, developers need to remember to change the analytics saga each time they add/remove a new route. This may seem not so important at first, but when the team is big or the app is complex, figuring out why things are broken is not trivial. 

In the end, developers are forced to maintain a list of actions that modify some part of state when all they really want is to listen that state mutation. This is a bad developer experience and leads to boilerplate code and bugs.
```js
if (state.currentPage !== previousState.currentPage)
  sendAnalyticsEvent()
```

There's a workaround in the redux/redux-saga and although it is in theory forbiden, it works surprisingly well:
```js
let previousCurrentPage
function* currentPageChanged() {
  while(true)
    yield take("*")
    const state = yield select()
    if (previousCurrentPage !== state.currentPage) {
      previousCurrentPage = state.currentPage
      sendAnalyticsEvent()
    }
  }
}
```

In Mobx/MobxStateTree it is simpler because you have `reactions` and `autoruns` precisely for that:
```js
reaction(() => state.currentPage, sendAnalyticsEvent)
```

## Proposal for Overmind

Right now in Overmind you can use `addMutationListener` in the `onInitialize` action, but I don't think it's a good API for this. I've been taking a look at the operators and I think there's a more elegant way to solve this.

So here is my proposal:

### The `waitForMutation` operator

This operator stops the pipe until the state mutates.  This is similar to Mobx's `reaction`.
```js
pipe(
  waitForMutation(({ state }) => state.currentPage),
  sendAnalyticsEvent
)
```

### The `waitUntilTrue` operator

This operator stops the pipe until the function returns true. This is similar to Mobx's `when`.
```js
pipe(
  waitUntilTrue(({ state }) => state.currentPage !== '/'),
  sendAnalyticsEvent
)
```

## Implementation idea

I've been taking a look the **Create custom operators** guide and these operators could be created with a new `createTrackOperator` where `context.state` uses a `getTrackStateTree`. I guess it would look like something like this: 

```js
export function waitForMutation(operation) {
  return createOperator(
    'waitForMutation',
    operation.name,
    (err, context, value, next) => {
      if (err) next(err, value)
      else {
        const tree = context.getTrackStateTree()
        operation({ ...context, state: tree.state }, value)
        tree.track(() => next(null, value))
      }
    }
  )
}
```

### The `startOver` operator

When reached, this operator starts again the pipe from the top.
```js
pipe(
  waitForMutation(({ state }) => state.currentPage),
  sendAnalyticsEvent,
  startOver
)
```

### The `race` operator

This has nothing to do with the issue topic but I thought it'd be cool to have a `race` operator with the combination of `startOver` for timetous and things like that :)

If `parallel` is like `Promise.all`, `race` is like `Promise.race`:
```js
pipe(
  race({
    succeed: fetchSomething,
    failed: wait(5000)
  }),
  when(_, ({ succeed }) => !!succeed, {
    true: doSomethingElse,
    false: startOver  // <- try it again
  })
)
```

----

By the way @christianalfoni, I saw you also used this type of `reactions` in your codesandbox refactoring:
https://github.com/cerebral/codesandbox-client/blob/sandbox/packages/app/src/app/pages/Sandbox/Editor/Content/index.js#L36

So I hope we are in the same boat here :)

**Comment by christianalfoni** [comment]
We are definitely in the same boat @luisherranz and thanks for a really great summary :-)

In early Overmind we actually did have `reactions`, though they were left out as it felt rushed. Also we do expose the low level APIs to make these things happen, so wanted to wait until we found a really good way to manage it.

So let me point out some challenges here:

1. When you use a callback to point to a piece of state, for tracking, it is perfectly okay if that state is a plain value... like a string, number etc. (`state.foo.myNumber`). The problem is when you point to an array or an object, which is also the case in Mobx. (`state.foo.items`)... do you expect the mutation listener to run only when the items array is replaced? Which is the behaviour now... or when whatever changes inside the array as well? I would expect the last, and this was an issue in Codesandbox actually. We had to artifically `map` over an error array to indicate that we were tracking that adding and removing of items. If we wanted to track properties on the errors themselves we would have to iterate the keys of each error object as well. The good thing with Overmind is that we are able to identify this and actually make this work out of the box. Though we have to make a decision. Should pointing to arrays/objects cause any nested change to also trigger the listener?

2. I like your suggestions on operators, I have actually talked to @fopsdev about this already, though you have taken it a step further :) The challenge though is that we do require you to actually call the action for the operator to be activated. Also if the operator is resolved, the action will resolve itself, meaning that you have to call it again. But maybe this is not such a big problem. In your example:

```js
export const sendAnalyticsOnPageChange = pipe(
  waitForMutation(({ state }) => state.currentPage),
  sendAnalyticsEvent
)
```

You could just call the action again at the end:

```js
export const sendAnalyticsOnPageChange = pipe(
  waitForMutation(({ state }) => state.currentPage),
  sendAnalyticsEvent,
  action(({ actions }) => actions.sendAnalyticsOnPageChange())
)
```

This would also show up very nicely in the devtools. As every time the action restarts it shows up as a new action, pending resolvement.

I also like the idea of create a `createMutationListenerOperator` 👍 

3. About `startOver. There is actually no way an operator could restart the action, cause operators are isolated and can be composed anywhere. So they only know about themselves. That means we can not restart a pipe etc. But it would be possible to maybe have a `runAction` operator which could have the signature of: `runAction((actions, value) => actions.doThis(value))`. That way you are in more control as well, also ensuring if a value should be passed to the action.

Yeah, `race` is definitely an operator we should implement, which would actually look pretty nice with `fork`:

```js
export const fetchSomething = pipe(
  race({
    succeed: fetchSomething,
    failed: wait(5000)
  }),
  fork((_, path) => path, {
    succeed: doSomethingElse,
    failed: doSomething
  })
)
```

But to implement retry here I think we would rather need an actual `retry` operator, so that you can control the number of times to retry and it depends on error throwing:

```js
export const fetchSomething = retry(
  pipe(
    race({
      succeed: fetchSomething,
      failed: wait(5000)
    }),
    fork((_, path) => path, {
      succeed: doSomethingElse,
      failed: throwAnErrorWhichTriggersRetry
    })
  ),
  3
)
```

But yeah... there are so many exciting things we can do here :) Let us focus on the mutation operators first and see where we go from there :)

**Comment by luisherranz** [comment]
I finally had some time to sit down today :)

I've started a PR for this: https://github.com/cerebral/overmind/pull/246

> do you expect the mutation listener to run only when the items array is replaced? Which is the behaviour now... or when whatever changes inside the array as well?

Yeah, I saw that observing arrays in Overmind works different than in Mobx. I think it should be the same than the default behavior of Overmind.

> The challenge though is that we do require you to actually call the action for the operator to be activated.

Yes, I think so. It give more control to the developer. If they want to trigger some of them in the `onInitialize` they can do so, but maybe others only make sense after the user has done something in the app.

> Also if the operator is resolved, the action will resolve itself, meaning that you have to call it again.

Yes. Or implement a `startOver` operator :)

**Comment by christianalfoni** [comment]
Okay, we got these now 😄
