### ISSUE TITLE
Namespacing limitations or approach

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#262]
New to overmind, but namespacing seems to be causing me problems. Is it desirable to keep things as denormalized as possible and avoid namespacing alltogether?

1. One thing I run into is, you can't `Derive<>` from another namespace.

2. Second is, if you want to send state from one namespace to another with an action (just copy one object to the other, you end up with proxy duplication errors.

Am I wrong on 1? And is 2 possible without cloning objects?

**Comment by christianalfoni** [comment]
Hi there :)

1) You can derive from other namespaces. The second argument passed into the derived function is the root state. The reason we pass in the "related state" as the first argument is because that is most likely what you want to derive from :)

2) The proxy duplication error. Does it occur by only passing the object as a value to the action or are you using that action to set the value into the state tree? Objects/arrays can not live in multiple places in the tree. Do you have a code example?

**Comment by natew** [comment]
Deriving from other spaces using the second argument is very helpful. Definitely would be great in the docs. I’ll try a PR this week at some point. 

I was passing existing state to an action in another namespace, and then attempting to set that into the other namespace state.

**Comment by christianalfoni** [comment]
Ah, yeah, we could definitely insert it in the "defining state" guide... though we do have it here: https://www.overmindjs.org/api/derive?view=react&typescript=true :)

Aha, I see. Objects can only live "in one place". This is a limitation, but is also a good thing as making changes to your state can only happen at "one address" in the tree. The way you solve this is using references: https://www.overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=true#defining-state-references

If you give me some more info on the scenario I can help you out structuring it, as it can help writing more docs on the subject :)

**Comment by christianalfoni** [comment]
Gettin' old
