### ISSUE TITLE
how to prevent whole app rerender on React

### ISSUE THREAD

**Issue by sirpy** [cerebral/overmind#269]
From my initial experiments it seems that every component that uses overmind is rerendered when state is changed and not only when the specific state variables it uses changes.
Is that the expected behaviour?
Would namespacing solve that? or there's another way?

**Comment by cjk** [comment]
I'm also a bit puzzled about this.
In theory, the [docs](https://overmindjs.org/guides/beginner/06_usingovermindwithreact?view=react&typescript=false) say:

> Rendering
> When you use the Overmind hook it will ensure that the component will render when any tracked state changes.
> It will not do anything related to the props passed to the component. That means whenever the parent renders, this
> component renders as well. You will need to wrap your component with REACT.MEMO to optimize rendering caused by a
> parent.

But I'm not sure what that means. Do we need to wrap every component with an overmind-controlled parent in a React-Memo?

**Comment by christianalfoni** [comment]
@sirpy @cjk I will note this in the docs.

Even though hooks are amazing, they come with a huge drawback related to higher order components which is what state management solutions has been using until now. Higher order components did not only expose state, they also made the component Pure. Meaning they acted as "render short circuits", preventing React from doing unnecessary reconciliation down the component tree. With hooks there is no way to do this interception, you will have to use `memo` components on your own. 

Typically this is not an issue, because state high up in the component tree is typically state you rarely change. But if you for example would do:

```js
function AppComponent () {
  const { state, actions } = useOvermind()

  return (
    <div>
      <input value={state.inputValue} onChange={actions.onInputChange} />
     <TheRestOfTheApp />
    </div>
  )
}
```

That would of course be an issue, as React would reconcile all your components on every change on the input... but this is not something you would do in practice. So I see the technical aspect of it, but not in practice :) 

I am trying to suggest to the React team that "no props" components should not reconcile when the parent reconciles, because there is no reason to. That would cause a natural "short circuit" in apps using external state management. But yeah, we will see: https://twitter.com/christianalfoni/status/1136699374136958976

I will update the docs so this becomes more clear. Thanks for a good question and please continue the discussion if anything is unclear :)

**Comment by cjk** [comment]
Hey @christianalfoni - thank you for the clarification, that helped a lot!

**Comment by christianalfoni** [comment]
Great :) Let me close this and added this update to a roadmap issue I am working on :)
