### ISSUE TITLE
Guides: Implementing UI - calling createHook in overmind/index.ts

### ISSUE THREAD

**Issue by schabluk** [cerebral/overmind#274]
Hi,

In the "Implementing UI" section of [Getting Started](https://overmindjs.org/guides/beginner/01_getstarted?view=react&typescript=true) guide, the `createHook` is called from `overmind/index.ts` - is there any particular reason to do that?

IMO it would make more sense, to call this function outside of the store, as it is specific to react. For example, this would work as well:
```javascript
import * as React from 'react'
import { createHook } from 'overmind-react'

const useOvermind = createHook()

const Count: React.FunctionComponent = () => {
  const { state, actions } = useOvermind()

  return (
    <div>
      <button onClick={() => actions.setCount(-1)}>-1</button>
      {state.count}
      <button onClick={() => actions.setCount(1)}>+1</button>
    </div>
  )
}

export default Count
```
On could even extract `useOvermind` hook creation to another file, like `hooks/index.ts`.

**Comment by Yonben** [comment]
The reason is that the hook is something you create once and then use all over your app.
You could definitely extract it to its own folder/file but then you'll import the config from the overmind folder to export the hook. To me, it makes sense to make it part of the "store configuration" file.

**Comment by schabluk** [comment]
> but then you'll import the config from the overmind folder to export the hook.

That's fine. I'd rather have overmind as a dependency in my hook, than crating hooks where the state is defined. State should be isolated, because If I wan't to use it with CLI application, I don't need to install `overmind-react`.

And actually, I think I don't need to import `Config` from the overmind folder, right? I can do:
```javascript
// hooks/index.ts
import { createHook } from 'overmind-react'
import { Config } from 'overmind'

export const useOvermind = createHook<Config>()
```
And that will work, because in `overmind/index.ts` i have declared:
```javascript
declare module 'overmind' {
  interface Config extends IConfig<typeof Config> {}
}
```
Am I right, or am I confusing something? :)

**Comment by Yonben** [comment]
Def right, my mistake. It's up to your preference then ;)

**Comment by christianalfoni** [comment]
@schabluk Insanely late response, but you make a good point!

Since you want to implement `useHook` several places I would suggest you want to put it into `hooks/index.js` or similar. But yeah, removing the dependency to `overmind-react` makes a lot of sense. 

Writing docs is a bit difficult cause you wanna give the whole idea with as little code as possible. And devs are pretty sensitive reading docs the first time. If we were to introduce another file, with an other export it would make things look more complicated than it really is and also make the docs a bit "messy".

So yeah, all thumbs up from me on your thoughts and approach!
