### ISSUE TITLE
Action not accepting async function

### ISSUE THREAD

**Issue by natew** [cerebral/overmind#277]
When I type a function as an Action, with overmind 0.19, it seems not to like the Promise return type:

![image](https://user-images.githubusercontent.com/12100/59375888-efda7300-8d03-11e9-8bf4-bd14e9f6afe9.png)

**Comment by louisgv** [comment]
Getting this same error too. I think this is introduced by Typescript > 3.4.5.

**Comment by louisgv** [comment]
Oh I found out that there's a new type `AsyncAction` that  should solve this problem!

**Comment by natew** [comment]
Why the split? It’s usually easy to type things as returning promise or not
and would be a lot simpler.

**Comment by corlaez** [comment]
Oh yeah I remember that I stumble upon this when updating. Yeah to be honest I don't know why the split.

**Comment by corlaez** [comment]
@natew you could ask this on discord, would you consider to close this as you already figured out how to make it work?

**Comment by natew** [comment]
It’s a legit request! No need to close without a good answer it will serve as a place for others looking. Never understood the desire to close things without any resolution.

**Comment by garth** [comment]
It's because the typing is now much stricter (more correct) the in the more recent overmind releases. An async function has a different signature, the type returned is not the same, so you cannot use the same interfaces to define it.

You will appreciate this even more if you use the [explicit typing approach](https://overmindjs.org/guides/beginner/05_typescript?view=react&typescript=false#typescript-two-typing-approaches-2.-explicit-typing) (which I highly recommend). It makes it much harder to make mistakes, since the TS compiler will pick up issues and assist you as you code.

This kind of discussion is much easer on discord, and everyone is happy to help.

**Comment by natew** [comment]
@garth I appreciate your reply but I don't see exactly what the reason is. You can always infer if something is async or not using typescript, so internally Overmind could just infer based on if the function returns a promise. Then, you wouldn't need to be changing between Action/AsyncAction, learning about the difference, as well as importing multiple definitions.

Basically, what is it giving the *end user*? I don't see any difference on my side, I already can see if it returns a promise or not and Overmind can too internally if it wants too, why am I having to annotate it? Do async actions have some other abilities I'm missing that make this necessary?

**Comment by garth** [comment]
If you don't want strong typed actions, you can still use regular JS, then you can go ahead and just skip the typing all together and return whatever you want, in most cases it will probably work.

But for larger or more complex apps, having the type system guarantee input and output gives you a lot. You can now call an action and wait for the response. Typescript will ensure that you handle the response correctly via a promise or not, you don't have to check the response every time just to be sure like you had to with JavaScript.

**Comment by natew** [comment]
That’s a bad faith explanation, it doesn’t grapple with the point I’m
clarifying and at once raises a false dichotomy / appeal to extreme, and a
no real Scotsman at once.

You’d still have it typed, accurately, and with a differentiation between
async and sync known at both in the user and library level. I don’t go
around typing every async function with an extra `IsAsyncFunction` type, do
you? Why not? Because typescript infers “async”. Likewise I doubt you type
every `const x = 1` with a :number. My actions are all const.

My question remains, I pose it without attempting to attack anyone’s
ideology and in good spirit, what does it actually do for the user to have
the distinguishing types here? It’s possible I’m missing something, so I’m
happy to be corrected. From what I see there’s literally no difference
given Overmind made Action infer the return type, besides typing more.

**Comment by henri-hulski** [comment]
I remember there was some discussion about it on discord and there was a proper reason to separate them.
I really think the best place to ask is on discord as the developers are quite active there and normally you get instantly an answer in a really friendly atmosphere.

**Comment by christianalfoni** [comment]
Yeah, this might not have been the best design decision. But many developers does not know that `async` functions are just functions returning promises. So I wanted to prevent that confusion... and thus, confusing those who know it 😂 

But, a lesson learned is that mixing Typescript and Javascript causes so many issues. If this was a Typescript only lib we would be a lot more comfortable using "empty functions" to get inference. Like having an `action` function instead of an `Action` type... where everything was just inferred.
