### ISSUE TITLE
How to deal with relationships between entities?

### ISSUE THREAD

**Issue by williamoliveira** [cerebral/overmind#315]
Typically with Redux Id normalize my data so if I need to update an entity it changes everywhere else, how Id do it with overmind?

**Comment by corlaez** [comment]
An example is better than a thousand words...
https://codesandbox.io/embed/react-overmind-list-sync-8e2v1?fontsize=14

The topic is also in the docs:
https://overmindjs.org/guides/intermediate/01_managinglists?view=react&typescript=true

However I do want to mention a thing that is on the docs:
Make sure that the renderer component (In my example TodoInput) calls useOvermind() . This ensure he will get updates. For my example it was necessary to do so but in some other examples you could pass a data object to a simple renderer that does not need to inspect overmind's state or actions. If you want that renderer to keep that object in sync with overmind's state make sure you call useOvermind.

**Comment by williamoliveira** [comment]
In the "Post" example, what if my posts have an "Author", can I store the data normalized but  access it like `post.author`?

with MobX I can use a getter

```ts
authorId: string

get author() {
   return this.storeSomewhere.authors[this.authorId]
}
```

**Comment by corlaez** [comment]
You can build a similar feature with the information in [cached getter (deriving state)](https://www.overmindjs.org/guides/beginner/02_definingstate?view=react&typescript=true#defining-state-deriving-state-cached-getter)

I recommend cached getter because you don't seem to need any param to make it work but you do need the whole state tree.
