### ISSUE TITLE
[BUG] React useEffect does not fire on Overmind state change when the app is wrapped in <React.StrictMode>

### ISSUE THREAD

**Issue by mpinter** [cerebral/overmind#391]
Hello,

a minimal example is reproduced here - https://codesandbox.io/s/overmind-example-f58w0?file=/src/components/App.js - it seems to break as long as the `<React.StrictMode>` wraps the `<Provider>` and the rest of the app, once that is removed everything works as expected.

The core of the issue is this:

```js
const { state, actions } = useOvermind();

  console.log("in render", state.title);
  useEffect(() => {
    console.log("I would expect this every 3 seconds, but it runs only once");
    console.log("in effect" + state.title);
    setTimeout(() => {
      console.log("Changing user id now!");
      actions.exampleAction(Date.now().toString());
    }, 3000);
  }, [actions, state.title]);
```

You can see the `state.title` updated in the 'in render' log but the effect not being trigerred on it's change.

Thanks for all the work on this great library. Cheers!

**Comment by qk0106** [comment]
Same issue here.

**Comment by christianalfoni** [comment]
Will work on this after next release! 😄

**Comment by christianalfoni** [comment]
Okay, so we have a version of `overmind-react` running on `next` now. It turns out there are many libraries having challenges supporting strict/concurrent mode. It seems that we are lucky as Overmind exposes a "trackingtree" instance for every component, so we might dodge the memory leak issues: https://github.com/facebook/react/issues/15317

But this needs to be tested. So please install `@next` on all packages and see if things work. Will do more testing as well, try it on Codesandbox etc. But hopefully we got something working nicely here 😄 

Travis job: https://travis-ci.org/github/cerebral/overmind/builds/699623921

**Comment by christianalfoni** [comment]
This should be working now, please reopen if not 😄
