### ISSUE TITLE
Question: About mutating references

### ISSUE THREAD

**Issue by ksmsk** [cerebral/overmind#393]
I'm using overmind in my current project and i have to say that it's a big relief after mess of redux/reselect and their plugins. I have two questions:

1. Is is good practice to mutate passed reference or should i mutate it from state?
```ts
export const changeCompanyName: Action<{ company: ICompany; name: string }> = (_, { company, name }) => {
  company.name = name;
};
// OR
export const changeCompanyName: Action<{ companyId: string; name: string }> = ({state}, { companyId, name }) => {
  state.companyState.companies[companyId].name = name
};

```
2. Is there a cleaner way to reference data in tree like in [mobx state tree](https://mobx-state-tree.js.org/concepts/references)? currently i'm doing like this:

```ts
type State = {
  companies: Record<string, ICompany>;
  currentCompanyId: string | null;
  currentCompany: Derive<State, ICompany | null>;
};

export const state: State = {
  companies: {},
  currentCompanyId: null,
  currentCompany: (state) => {
    if (state.currentCompanyId && state.companies[state.currentCompanyId]) {
      return state.companies[state.currentCompanyId];
    }
    return null;
  },
};
```

Thanks for this awesome package. I will definitely continue to use overmind in the future.

**Comment by gabriel-peracio** [comment]
> Is is good practice to mutate passed reference or should i mutate it from state?

Due to it being proxied, I believe you can simply mutate it directly without having to manually traverse the tree. Might even be more performant if anything (since you're not hitting all the proxies in the chain), although I'd guess the gains would be negligible
> Is there a cleaner way to reference data in tree like in mobx state tree? currently i'm doing like this:

You probably have an event that reads reads the id from one of the entries in `companies` and writes that to `currentCompanyId`, right? Instead of that, simply store the whole company entry object to `currentCompany`.

I know it feels as though you'd be storing a duplicate, but you're storing a reference. Afterwards, these two should be the same thing:
```javascript
currentCompany.name = "myCompany";
```
```javascript
companies[state.currentCompanyId] = "myCompany";
```
which means this should work:
```javascript
currentCompany.name = "myCompany";
console.log(currentCompany.name); // outputs "myCompany";
companies[state.currentCompanyId].name = "changed name";
console.log(currentCompany.name); // outputs "changed name";
currentCompany.name = "another name";
console.log(companies[state.currentCompanyId].name); // outputs "another name";
```

**Comment by ksmsk** [comment]
@gabriel-peracio thanks for input.

> I know it feels as though you'd be storing a duplicate, but you're storing a reference.

I honestly forgot it's just reference storing not copying object itself. That's make things even easier and cleaner as if this lib is not clean and easy enough. :)

**Comment by christianalfoni** [comment]
It makes me so happy when I see the community interacting 😍 

Glad you figured it out! Let me know if you have any more question!
