### ISSUE TITLE
[BUG] Namespaced Statecharts do not respect transitions when entry: used

### ISSUE THREAD

**Issue by grandevel** [cerebral/overmind#396]
Assume two overmind config domains - domA, domB. Each has actions,effects,state and statechart defined.

both statecharts look as follows:

export const someChart = {
  initial: 'INIT',
  states: {
    INIT: {
      entry: 'doSomething',
      on: {
        doSomething: 'ANOTHER_STATE',
      },
    },
    ANOTHER_STATE: {
      on: {
      ...
      },
    },

**overmind/index.js:**
export const useOvermind = createHook();
export const config = namespaced({ domA, domB });

Problem:

With NO namespaces in play, a chart goes to initial state, fires doSomething() and transitions to ANOTHER_STATE. However with namespaces in play, the entry: fires doSomething() correctly, but does not transition state.

However, calling actions.domA.doSomething() from a button in the app or via the devtools does make the transitions work correctly. Therefore I believe that entry: is not correctly transitioning state when namespaced, or the statechart transitions are not being 'listened to' early enough (i.e. some sort of timing issue).

**Comment by christianalfoni** [comment]
Hi @grandevel and thanks for testing this out a writing awesome issues! The next release will be focused on statecharts, so I will dive into this then 😄

**Comment by christianalfoni** [comment]
Hi there!

Okay, so I took a look at this and I do not see how this could have worked in any of the scenarios 🤔 

The reason is that any of the actions run by entry, exit or the transition does not re-trigger the statechart, they just run the action underneath. Changing this adds quite a bit of complexity, which I do not currently think is needed.

So the way I would solve your scenario is to rather do this:

```ts
export const someChart = {
  initial: 'INIT',
  states: {
    INIT: {
      entry: 'onInit',
      on: {
         doSomething: 'ANOTHER_STATE',
      },
  },
  ANOTHER_STATE: {
    on: {
      ...
    },
},
```

And inside `onInit` I would:

```ts
export const onInit = ({ actions }) => actions.doSomething()
```

I understand it might seem unnecessary, but I have to balance maintenance and complexity of the project VS use cases, and this use case is not very typical. And also it can be solved very straight forward like the example above 😄 

Please let me know if I misunderstood anything here and I hope it made sense!

**Comment by grandevel** [comment]
Sure, that is a fine solution by me... but could we document it? Span the wheels on that for a few hours. For additional beer, maybe throw a 'Warning: entry/exit state will retrigger statechart' when the entry/exit action is also detected as an on: entry in the same state and in dev mode.

**Comment by christianalfoni** [comment]
Haha, will do 😉

**Comment by christianalfoni** [comment]
Okay, documented on the **entry** action documentation 😄
