### ISSUE TITLE
[BUG] Derived types not resolved in TypeScript 3.9

### ISSUE THREAD

**Issue by geirsagberg** [cerebral/overmind#399]
To reproduce:

1. Make a type with a derived member
2. See that `ResolveState` correctly unwraps the `Derive` type in TS 3.8:
![image](https://user-images.githubusercontent.com/594564/82063132-64175680-96cb-11ea-8cde-74d642b1bfdb.png)
3. Change TS to 3.9 and see that the type is no longer unwrapped:
![image](https://user-images.githubusercontent.com/594564/82063206-7e513480-96cb-11ea-8024-06afd8bd4379.png)
4. Any attempt to use the derived state will not compile.

Not sure if this is a TS bug or just a result of stricter type checking in 3.9...

**Comment by christianalfoni** [comment]
Hi @geirsagberg !

Yes, I am not exactly sure what happened with TS 3.9. As I understand interfaces are supposed to be evaluated lazily and that way allowing circular typing, but something changed here. It might be a bug. 

But! In the previous version of Overmind we flipped to a `derived` factory instead of using the type. It allows you to define your state type in plain values. 

```ts
import { derived } from 'overmind'

type State = {
  foo: string
}

export const state: State = {
  foo: derived<State, string>(state => state.foo)
}
```

The documentation was also updated to be "the blessed way" to type derived, but did not foresee the `Derive` type to actually breaking in TS... but good thing we have the other approach which works 😄 

It will require so refactoring, so sorry about that, but hopefully the `derived` factory feels more natural 😄

**Comment by christianalfoni** [comment]
Actually,

I am working on exposing a `createState` factory. This will allow for a much smoother state creation. It works like this:

```ts
const state = createState<{
  foo: string
  shoutedFoo: string
}>({
  foo: 'foo',
  shoutedFoo: state => state.foo + '!!!'
})
```

Basically you just define the types and at definition time you choose if you want to express it as a value or a derived

**Comment by christianalfoni** [comment]
Oh! wait wait wait...

It is actually a rule about `typeof`, so you just have to:

```ts
declare module 'overmind' {
  interface Config extends IConfig<{
    state: typeof state
    actions: typeof actions
    effects: typeof effects
  }> {}
}
```

I will update docs

**Comment by christianalfoni** [comment]
Okay, this still does not fix `Derive`... but it is necessary to move to TS 3.9. So the `derived` is the way to go as that is the only way currently known to handle the circular typing of derived state.

**Comment by christianalfoni** [comment]
Next release will fix this once and for all, also giving some new capabilities. Stay tuned tomorrow 😄
