### ISSUE TITLE
[BUG] useOvermind/App hook does not detect changes in memo components

### ISSUE THREAD

**Issue by darkowic** [cerebral/overmind#405]
Usage of the hook inside the memoized component doesn't trigger rerender on change.

Reproduced in https://codesandbox.io/s/overmind-bug-hook-czuwe?file=/src/index.js

Initial state:
![useOvermindBugBefore](https://user-images.githubusercontent.com/11510581/83331825-8ea30b00-a298-11ea-99aa-bddba597c6e6.jpg)
After moving elements to the second list:
![useOvermindBugAfter](https://user-images.githubusercontent.com/11510581/83331844-9d89bd80-a298-11ea-8c3c-9ce63d959b2a.jpg)

**Comment by christianalfoni** [comment]
Hm, being a `memo` component should not have any effect on this. I will check it ASAP

**Comment by christianalfoni** [comment]
Oh, I looked at the example now and this is actually correct behaviour. The reason MEMO does not rerender is because you are passing the `elements` array to the component. When you do `splice`, this array does not change, which means MEMO does not see any change.

Also the component itself never looks at the `elements` itself, it looks at the items of the array, which you see in the devtools. It looks at `...elements.0.id` etc., while the App actually looks at `...elements`.

I totally see why this is confusing and we can write more explicit docs here. Basically it means that when you pass an array or an object to a component you will only observe whatever you access in the array/object, not the array/object itself.

If we were to change this behaviour I worry about it causing other issues, like rendering too much. So basically, if you want to pass the elements down to the memo component I would in this case pass down `dataIndex`, where the component does:

```ts
const Comp ({ dataIndex }) => {
  const data = useAppState().data[dataIndex]
  data.id
  data.elements
}
```

I hope this makes sense, and I have updated the docs with more information on this. Please reopen if you want to discuss further 😄
