### ISSUE TITLE
[QUESTION] What happened to Dynamic getters

### ISSUE THREAD

**Issue by Freak613** [cerebral/overmind#425]
Previously, there was a section in the documentation on how to do dynamic getters (parameterized selectors).
I still can found it in  v22  docs. But now this section just disappeared without any mention on how to handle this situation with new `derived` API.

**Comment by amrdraz** [comment]
they're references at the end of the state documentation in [the section about references](https://overmindjs.org/core/defining-state#exposing-the-state)

They also still appear in the state as class declaration approach

**Comment by Freak613** [comment]
Sorry but I can't find any mentions about dynamic getters or their equivalent in current (v25) docs.
Neither references nor class declaration.

Just to be clear, I'm talking about this section:
https://overmindjs.org/v/master/core/defining-state#dynamic-getter
and code like this:
```javascript
export const state = {
  users: {},
  userById: ({ users }) => id => users[id]
}
```
The `id` is what makes `userById` dynamic getter, the one where I can pass parameters into.

**Comment by markmccoid** [comment]
Did you ever figure this out?  I have the same question.

**Comment by markmccoid** [comment]
Not sure if this is what was intended, but you can get the dynamic getters working using the following syntax:

export const state = {
  users: {},
  userById: derived(({ users }) => id => users[id])
}

**Comment by Freak613** [comment]
@markmccoid I think in your case this getter will not hit memoization. Basically you return new function on each state change, but the function itself is not properly memoized. 
However your implementation helped me to suggest that following approach could work:
```javascript
export const state = {
  users: {},
  userById: derived(({ users }) => {
    // use lodash `memoize` or any basic memoization solution
    return memoize(id => users[id])
  })
}
```
Here on each state change we instantiate new memoization cache for nested function. It can help to achieve target optimization in most cases.
I think the fact that it's not straightforward but people struggle with it, is worth mentioning in docs or some recipes section.

**Comment by christianalfoni** [comment]
Hi there and sorry for late response!

If my memory serves me right are I wrote a rant somewhere about why dynamic getters are problematic 😄 But the gist of it is that you can memoize manually if needed, as you do here.

That said, memoization should rather be used when you have heavy calculation in your derived, not for simple getters like this. The reason is that the function will actually not be replaced, it will always be the same as the derived scope itself does not track any state. Rather the state accessed when calling the returned function will be tracked by whatever is calling it, which is exactly what you want 😄 

I will update the docs with this. Please reopen if any more questions.

**Comment by christianalfoni** [comment]
IT should be here: https://overmindjs.org/core/defining-state#derived ... does not seem to be active yet, but is merged, so pops up soon
