### ISSUE TITLE
[Question] Resetting state

### ISSUE THREAD

**Issue by amursky** [cerebral/overmind#500]
What is the best (the easiest) way to reset a part of the state?

For example:
```
{
  a: {
    b: 123,
    c: derived(...)
  },
  d: { ... }
}
```

How do I reset "a" to its initial state?

**Comment by laffed** [comment]
I've been wanting to write a method for this feature for a while now. 
For now how I handle this is to create a reset action. This works okay for my application because I will typically reset the ENTIRE state object. But you could customize it by passing in params to your action. 

For example in my user/state.ts
`
type State = {
  userid: string;
  fullname: string;
  isLoggedIn: boolean;
}

export const state: State = {
  userid: '',
  fullname: '',
  isLoggedIn: false
}
`

then in my user/actions.ts
`
export const resetUserState: Action<void, void> = ({state}) => {
  state.user = {
     userid: '',
     fullname: '',
     isLoggedIn: false
   }
}
`

**Comment by laffed** [comment]
to customize it you might pass in an array of params that you DON'T want to be reset. If you did it the other way around it may get tricky with nested object states

```

export const resetUserState: Action<string[], void> = ({state}, arr) => {
   const originalState = {
      userid: '', 
      fullname: '',
      isLoggedIn: ''
    };
    
    for (let key in  state) {
       if (arr.indexOf(key) === -1) {
          state.user[key] = originalState[key];
        }
     }
}
```

**Comment by amursky** [comment]
@laffed, thank you!

**Comment by laffed** [comment]
@christianalfoni requesting issue closed
